roles:
  admin:
    display_name: 管理员
    permissions:
      - user:create
      - user:retrieve
      - user:update
      - user:delete
      - group:create
      - group:retrieve
      - group:update
      - group:delete
      - permission:retrieve
      - dataset:create
      - dataset:retrieve
      - dataset:update
      - dataset:delete
      - document:download
      - document:upload
      - document:delete
  user:
    display_name: 普通用户
    permissions:
      - auth:wx_login
